### ISSUE TITLE
ADR-Prime

### ISSUE THREAD

**Issue by ResinSmoker** [mw5mercs-modding/yaml-docs#1]
Cockpit not show when using this mech. All mods current as of 2-3-2023 from Steam Workshop.

**Comment by trueg** [comment]
I suppose you wanted to post this on the YetAnotherClanMech project. ;)
The issue you are describing means that one of the hardpoints is broken. Can you figure out which one it is by removing one weapon after the other and seeing when the cockpit works again?

**Comment by ResinSmoker** [comment]
Sebastian,

No worries, should be able to confirm in a day or so.

Question: Why is it that mechs needing more power opt for larger / heavier
engines? Would think it to make more sense having two reactors for the
"equivalent" output but at a signifigantly reduced weight. Even if this
ment giving up critical locations to fit both units. Example: installing
two 150 rated reactors for a combined output of 300.

Kevin

**Comment by trueg** [comment]
Not sure what you mean regarding the engine cores. Only Superheavies need two engine cores, all other mechs can only run one. That is how it works in Battletech.

**Comment by ResinSmoker** [comment]
Sebastian,

The cockpit view worked once the center torso weapon was removed.

-Kevin

**Comment by trueg** [comment]
energy or missile or ballistic?

**Comment by ResinSmoker** [comment]
Sorry, it's an energy slot. Wad using a Clan Med. ER Laser.

**Comment by trueg** [comment]
thanks. Found the issue. Has been fixed for the next release.

**Comment by ResinSmoker** [comment]
Sebastian,

Thank you and sorry for the confusion.

-Kevin
