### ISSUE TITLE
YAML Mechs KGC Missile Hardpoint missing

### ISSUE THREAD

**Issue by M0Dark1** [mw5mercs-modding/yaml-docs#2]
Hi, Not sure if this is the right place to post this but...

There seems to be an issue with the KGC-001, and the KGC-CAR listing an additional missile hardpoint which you can't actually fit a weapon to. I.E. the tooltip and the X/X on the left of the screen in mechlab shows. 0/5 but there are only actually 4 hardpoints on the KGC-001, and 0/6 when there are only 5 available on the KGC-CAR. These are the only 2 variants I have collected so cannot confirm if the issue is across the whole King Crab chassis or just selected variants.

**Comment by trueg** [comment]
thanks. Will be fixed asap. :)
