### ISSUE TITLE
engine 210 has wrong weight

### ISSUE THREAD

**Issue by KRASK52** [mw5mercs-modding/yaml-docs#3]
![20230213132636_1](https://user-images.githubusercontent.com/65196383/218555648-d5e642ee-9941-4b5e-a980-b7a479ba6c54.jpg)

![20230213132640_1](https://user-images.githubusercontent.com/65196383/218555371-8ad2b4c9-488a-436d-9aae-c9cb11f18759.jpg)

engine says it is 9 tons adding it causes 10 tons to be added to mech

edit: missed an image

**Comment by trueg** [comment]
not a bug actually. The engine weight calc is a bit confusing. I do not know the exact values off the top of my head but it has to do with the gyro and engine heatsink weights. We are looking into improving the tooltips, etc, to make it clearer.
